### ISSUE TITLE
frequent crashes

### ISSUE THREAD

**Issue by felmue** [hpsaturn/m5stickc-dcf77-hat#1]
Hello there,

first of all, thank you very much for this repository.

I run the code on an M5StickCPlus and while it works ok the program from time to time crashes. Is that something you've encountered as well? Just curious.

I think it might have to do with the callback functions which are called from within the interrupt and on the ESP32 there are some restrictions regarding what's allowed in an interrupt and what not. I already removed all `Serial.print()` statements, but maybe writing to the screen is also problematic.

BTW: when I disable the callbacks I don't see any crashes anymore.

Thanks
Felix

**Comment by hpsaturn** [comment]
Thanks for the feedback and comments. And yes, I noticed too that it had some concurrency issues maybe. But in this moment I did some test but I not founded the fix to the problem, and after that I used my only M5StickCPlus in other development, then I forget it. But if you catch the fix to the problem, please don't forget make a pull request here. Thanks in advance 😊

**Comment by felmue** [comment]
Hello @hpsaturn 

[PR](https://github.com/hpsaturn/m5stickc-dcf77-hat/pull/2) to fix crash added.

Thanks
Felix

**Comment by hpsaturn** [comment]
Thanks! I'm going to merge it to devel for now, to perform a long test in the device. But I seen that everything are ok in the code review.

**Comment by hpsaturn** [comment]
resolved on #2 and added in the last release: 
https://github.com/hpsaturn/m5stickc-dcf77-hat/releases/tag/0.1.3
